Communication/urls.py
from django.conf.urls import url
from django.conf.urls import url
from .import views
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from . import views as uv

app_name = 'Communication'

urlpatterns = [
    url(r'^search_message/', uv.search_message, name='search_message'),
    url(r'^message_read/', uv.message_read, name='message_read'),
    url(r'^message_by_me/', uv.message_by_me, name='message_by_me'),
    url(r'^marked_message/', uv.marked_message, name='marked_message'),
    url(r'^chat/', uv.chat, name='chat'),
    url(r'^contact_us/', uv.contact_us, name='contact_us'),
    url(r'^write_message/', uv.write_message, name='write_message'),
    url(r'^person_message/', uv.person_message, name='person_message'),
    url(r'^system_message/',uv.system_message,name='system_message'),
    url(r'^(?P<message_id>[0-9]+)/notice_details/$', uv.notice_details, name='notice_details'),
    url(r'^(?P<message_id>[0-9]+)/message_details/$', uv.message_details, name='message_details'),
    url(r'^(?P<message_id>[0-9]+)/mark_by_receiver/$', uv.mark_by_receiver, name='mark_by_receiver'),

]

Send/urls.py
from django.conf.urls import url
from .import views
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

app_name = 'Send'
urlpatterns = [


    url(r'^send_category', views.send_category, name='send_category'),
    url(r'^add_order', views.add_order, name='add_order'),
    url(r'^filling_suc', views.filling_suc, name='filling_suc'),
    url(r'^(?P<task_id>[0-9]+)/send_details/$', views.send_details, name='send_details'),
    url(r'^(?P<task_id>[0-9]+)/reset/', views.reset, name='reset'),

    url(r'^recommend_master', views.recommend_master, name='recommend_master'),
    url(r'^popular_master', views.popular_master, name='popular_master'),
    url(r'^(?P<master_type_id>[0-9]+)/masters_category/$', views.master_category, name='master_category'),
    url(r'^masters', views.masters, name='masters'),
    url(r'^(?P<master_id>[0-9]+)/master_details/$', views.master_details, name='master_details'),
    url(r'^(?P<master_id>[0-9]+)/add_order_of_master/$', views.add_order_of_master, name='add_order_of_master'),
    url(r'^master_like', views.master_like, name='master_like'),
    url(r'^master_favorite$', views.master_favorite, name='master_favorite'),
    url(r'^(?P<task_id>[0-9]+)/del_send_suc$', views.del_send_suc, name='del_send_suc'),

    url(r'^recommend_good', views.recommend_good, name='recommend_good'),
    url(r'^popular_good', views.popular_good, name='popular_good'),
    url(r'^(?P<good_type_id>[0-9]+)/good_category/$', views.good_category, name='good_category'),
    url(r'^goods', views.goods, name='goods'),
    url(r'^(?P<good_id>[0-9]+)/good_details/$', views.good_details, name='good_details'),
    url(r'^good_favorite/$', views.good_favorite, name='good_favorite'),
    url(r'^add_car', views.add_car, name='add_car'),

    url(r'^add_competition', views.add_competition, name='add_competition'),
    url(r'^suc', views.suc, name='suc'),
    url(r'^reset', views.reset, name='reset'),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WeHelp20/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.urls import path
from Login import views
from django.views.static import serve
from django.conf.urls.static import static
from Communication import views as uv
from Boards import views as boards_views
from django.contrib.auth import views as auth_views
from Login.views import ForgetPwdView, ResetView,  ModifyPwdView
from django.urls import re_path
from django.views.generic.base import RedirectView
from Send import views as sd
from Take import views as tk

urlpatterns = [
    url(r'^$', views.wehelp, name='wehelp'),
    url(r'^wehelp', views.wehelp, name='wehelp'),
    url('about_platform/', views.about_platform, name='about_platform'),
    url(r'^Send/', include('Send.urls')),
    url(r'^is_login', sd.is_login, name='is_login'),
    url(r'^Take/', include('Take.urls')),
    url(r'^admin/', admin.site.urls),
    url('register/', views.RegisterView.as_view()),
    path('login/', views.LoginView.as_view(),name='login'),
    path('logout/', views.logout_view),
    path('reset_pw/', views.reset_pw),
    path('tags/', views.tags),
    path('tags/new/', views.new_tags),
    path('send/', views.get_orders),
    path('task/', views.get_tasks),
    path('new_avatar/', views.new_avatar, name='new_avatar'),
    path('index/', views.index),
    path('collection/', views.get_collection),
    path('goodfavorite/', views.good_favorite),
    path('collection_c/', views.collection_c),
    path('disclamier/', views.disclaimer),
    path('map/', views.map),
    path('bar/', views.bar),
    path('doughnut/', views.doughnut),
    path('line/', views.line),
    path('linecus/', views.linecus),
    path('pie/', views.pie),
    path('piecus/', views.piecus),
    path('polar/', views.polar),
    path('radar/', views.radar),

    # 验证码以邮箱找回密码
    path("forget/", ForgetPwdView.as_view(), name="forget_pwd"),
    path("captcha/", include('captcha.urls')),
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name="reset_pwd"),
    path("modify/", ModifyPwdView.as_view(), name="modify_pwd"),

    url(r'^Communication/', include('Communication.urls')),

    url(r'^chat/', include('chat.urls')),

    url(r'^about_platform',uv.about_platform, name='about_platform'),
    url(r'^about_us/$', tk.about_us, name='about_us'),

    #url(r'^search',uv.search,name='search'),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^luntan/$', boards_views.BoardListView.as_view(), name='luntan'),
    url(r'^search_subject/$', boards_views.search_subject, name='search_subject'),
    url(r'^boards/(?P<pk>\d+)/$', boards_views.TopicListView.as_view(), name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', boards_views.new_topic, name='new_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', boards_views.PostListView.as_view(),
                      name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', boards_views.reply_topic, name='reply_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/complain/$', boards_views.complain, name='complain'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/luntanuser/$', boards_views.luntanuser,name='luntanuser'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
                      boards_views.PostUpdateView.as_view(), name='edit_post'),
    url(r'^edit_post2/$', boards_views.edit_post2, name="edit_post2"),
    url(r'^new_topic2/$', boards_views.new_topic2, name='new_topic2'),
    url(r'^complain2/$', boards_views.complain2, name="complain2"),
    url(r'^delete/$', boards_views.delete2, name='delete2'),
    url(r'^contact_us/$', boards_views.contact_us, name='contact_us'),
    url(r'^contact_way/$', boards_views.contact_way, name="contact_way"),
    url(r'^cooperation/$', boards_views.cooperation, name="cooperation"),
    url(r'^joinus/$', boards_views.joinus, name="joinus"),
    url(r'^boards/(?P<pk>\d+)/top/$', boards_views.top, name='top'),

    # 添加网站小图标
     url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^(?P<room_name>[^/]+)/(?P<user_name>[^/]+)/$', views.room, name='room'),
]

Login/models.py
from django.db import models
from django.conf import settings
from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.text import Truncator
import math
from datetime import datetime


# Login （个人信息模块）的models #

class MasterType(models.Model):
    type = (
        ('delivery', "快递"),
        ('procurement', "代购"),
        ('print', "打印"),
        ('umbrella', "共享伞"),
        ('others', "其他"),
    )
    master_type_id = models.AutoField(primary_key=True, verbose_name='商品类型')
    master_type_name = models.CharField(max_length=20, choices=type, default='delivery', null=True, blank=True, verbose_name='接单类型')


class User(AbstractUser):
    """
    用户资料
    """
    gender_choice = (
        (u'M', u'Male'),
        (u'F', u'Female'),
    )
    login = (
        ('0', u'离线'),
        ('1', u'在线'),
    )
    username = models.CharField(max_length=64, verbose_name='用户名', unique=True)
    name = models.CharField(max_length=64, blank=True, verbose_name='姓名')
    gender = models.CharField(max_length=2, choices=gender_choice)
    college = models.CharField(max_length=64, blank=True, verbose_name='学院')
    major = models.CharField(max_length=64, blank=True, verbose_name='专业')
    birthday = models.DateField(blank=True, null=True, verbose_name='生日')
    email = models.EmailField(blank=True, verbose_name='邮箱')
    qq_num = models.CharField(max_length=64, blank=True, verbose_name='QQ号')
    avatar = models.ImageField(upload_to='avatar', verbose_name='头像')

    final_remark = models.FloatField(max_length=10, null=True, blank=True, verbose_name='总评分')
    task_take_num = models.IntegerField(default=0, blank=True, verbose_name='接单总次数')
    alike = models.IntegerField(default=0, blank=True, verbose_name='点赞总次数')
    attention = models.IntegerField(default=0, blank=True, verbose_name='关注总次数')

    is_login = models.CharField(max_length=128, choices=login, default='0', verbose_name='')

    master_type = models.ForeignKey(MasterType, on_delete=models.CASCADE, blank=True, null=True, verbose_name='达人类型')

    become_master_datetime = models.DateTimeField(auto_now_add=True, verbose_name='成为达人时间')
    master_take_delivery_times = models.IntegerField(default=0, blank=True, verbose_name='接快递总次数')
    master_take_buy_times = models.IntegerField(default=0, blank=True, verbose_name='接代购总次数')
    master_take_print_times = models.IntegerField(default=0, blank=True, verbose_name='接打印总次数')
    master_take_umbrella_times = models.IntegerField(default=0, blank=True, verbose_name='接共享伞总次数')
    master_take_others_times = models.IntegerField(default=0, blank=True, verbose_name='接其他单次数')

    class Meta:
        verbose_name = '用户资料'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username

# Login （个人信息模块）的models #


# Send （发单模块）和Take（接单模块） 的models #

class TaskSend(models.Model):
    """
    发单信息
    """
    state = (
        ('0', "未接单"),
        ('1', "已接单"),
    )
    type = (
        ('delivery', "快递"),
        ('buy', "代购"),
        ('print', "打印"),
        ('umbrella', "共享伞"),
        ('others', "其他"),
    )
    task_id = models.AutoField(primary_key=True, verbose_name='订单ID')
    task_category = models.CharField(max_length=128, choices=type, default='delivery', null=True, blank=True, verbose_name='分类')
    task_time = models.DateTimeField(max_length=128, verbose_name='任务时间', null=True)
    task_place = models.CharField(max_length=128, verbose_name='任务地点')
    task_reward = models.IntegerField(blank=True, verbose_name='报酬')
    task_details = models.CharField(max_length=128, blank=True, verbose_name='详情')
    task_send_time = models.DateTimeField(auto_now_add=True, verbose_name='订单发出时间')
    task_img = models.ImageField(upload_to='task_img', null=True, default='avatar/default.png', verbose_name='发单图片')
    sender = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='发出者')
    task_state = models.CharField(max_length=128, choices=state, default='0', null=True, blank=True, verbose_name='是否被接')
    send_collection_times = models.IntegerField(default=0, blank=True, verbose_name='被收藏次数')

    class Meta:
        ordering = ["task_send_time"]
        verbose_name = "发单表"
        verbose_name_plural = "发单表"


class MasterLike(models.Model):
    """
    对达人点赞
    """
    master = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='被赞者', related_name='be_like')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='点赞用户', related_name='like')
    like_time = models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')

    class Meta:
        ordering = ["like_time"]
        verbose_name = "点赞"
        verbose_name_plural = "点赞"


class MasterFavorite(models.Model):
    """
    关注达人
    """
    master = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='被关注者', related_name='be_fav')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='粉丝', related_name='fav')
    fav_time = models.DateTimeField(auto_now_add=True, verbose_name='关注时间')

    class Meta:
        ordering = ["fav_time"]
        verbose_name = "关注"
        verbose_name_plural = "关注"


class GoodType(models.Model):
    """
    商品类型
    """
    type = (
        ('food', "食物"),
        ('cloth', "衣服"),
        ('furniture', "家具"),
        ('book', "书籍"),
        ('stationary', "文具"),
        ('others', '其他'),
    )
    good_type_id = models.AutoField(primary_key=True, verbose_name='商品类型')
    good_type_name = models.CharField(max_length=20, choices=type, default='食物', null=True, blank=True, verbose_name='商品类型')

    class Meta:
        ordering = ["good_type_id"]
        verbose_name = "商品类型"


class Good(models.Model):
    """
    商品
    """
    good_id = models.AutoField(primary_key=True, verbose_name='商品ID')
    good_sender_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='卖家')
    good_portrait = models.ImageField(upload_to='good_img', default='avatar/default.png', verbose_name='商品图片')
    good_name = models.CharField(max_length=20, default="", verbose_name='商品名称')
    good_prize = models.FloatField(max_length=128, verbose_name='价格')
    good_description = models.CharField(max_length=256, blank=True, verbose_name='描述')
    good_time = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='发出时间')
    good_category = models.ForeignKey(GoodType, on_delete=models.CASCADE, verbose_name='商品分类')
    fav = models.IntegerField(default=0, blank=True, verbose_name='收藏总次数')
    car = models.IntegerField(default=0, blank=True, verbose_name='加入购物车总次数')

    def __str__(self):
        return self.good_name


class GoodCar(models.Model):
    """
    购物车
    """
    good = models.ForeignKey(Good, on_delete=models.CASCADE, verbose_name='购物车的商品')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='加入者')
    add_car_time = models.DateTimeField(auto_now_add=True, verbose_name='加入购物车时间')

    class Meta:
        ordering = ["add_car_time"]
        verbose_name = "Pie"
        verbose_name_plural = "加入购物车"


class GoodFavorite(models.Model):
    """
    收藏商品
    """
    good = models.ForeignKey(Good, on_delete=models.CASCADE, verbose_name='收藏的商品')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='收藏者')
    favorite_time = models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')

    class Meta:
        ordering = ["favorite_time"]
        verbose_name = "收藏"
        verbose_name_plural = "收藏"


class TaskTake(models.Model):
    """
    订单信息
    """
    state = (
        ('0', "已完成"),
        ('1', "未完成"),
    )
    task_take_id = models.AutoField(primary_key=True, verbose_name='订单ID')
    task_taker_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='接单ID')
    task_send_id = models.OneToOneField(TaskSend, on_delete=models.CASCADE, verbose_name='发单表')
    task_take_time = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='接单时间')
    task_take_state = models.CharField(max_length=32, choices=state, default="1", blank=True, null=True, verbose_name='订单状态')
    task_take_mark = models.FloatField(max_length=128,  blank=True, null=True, verbose_name='订单评分')

    def __str__(self):
        return str(self.task_taker_id)


class Collection(models.Model):
    """
    收藏的发单
    """
    collection_id = models.AutoField(primary_key=True, verbose_name='收藏ID')
    collection_collector_id = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='收藏者')
    collection_thing_id = models.ForeignKey(TaskSend, on_delete=models.CASCADE, verbose_name='收藏的商品')
    collection_time = models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')

    def __str__(self):
        return str(self.collection_id)


class Competition(models.Model):
    """
    大赛
    """
    competition_id = models.AutoField(primary_key=True)
    competition_sender_id = models.ForeignKey(User, on_delete=models.CASCADE,)
    competition_poster = models.ImageField(upload_to='competition_img', verbose_name='大赛海报')
    competition_title = models.CharField(max_length=50, default="", verbose_name='大赛主题')
    competition_description = models.CharField(max_length=200, verbose_name='大赛简介')
    competition_time = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='发布时间')
    competition_colletion_times = models.IntegerField(default=0, blank=True, verbose_name='收藏次数')


class CollectionCompetition(models.Model):
    """
    收藏的比赛
    """
    collectioncompetition_id = models.AutoField(primary_key=True, verbose_name='收藏比赛ID')
    collectioncompetition_thing_id = models.ForeignKey(Competition, on_delete=models.CASCADE, verbose_name='收藏的比赛')

templates/communication/message_by_me.html
{% extends 'accounts/base.html' %}

{% load staticfiles %}

{% block title %}
已发私信
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">

{% endblock %}

    {% block content %}
<div class="nav1">
               <div class="item home">
                   <img src="{% static 'images/icon/system_message.jpg' %}" class="nav-img">
                    <a href="{% url 'Communication:system_message' %}">系统通知</a>
               </div>
               <div class="item">
                   <img src="{% static 'images/icon/person_message.jpg' %}" class="nav-img">
                   <a href="{% url 'Communication:person_message'%}">收信箱</a>
               </div>
               <div class="item">
                   <img src="{% static 'images/icon/message_by_me.jpg' %}" class="nav-img">
                   已发私信
               </div>
              <div class="item">
                  <img src="{% static 'images/icon/message_marked.jpg' %}" class="nav-img">
                  <a href="{% url 'Communication:marked_message'%}">特别标注</a>
              </div>
                <div class="item">
                    <img src="{% static 'images/icon/chat.jpg' %}" class="nav-img">
                    <a href="{% url 'Communication:chat'%}">聊天室</a>
               </div>
                <div class="item">
                    <img src="{% static 'images/icon/message_read.jpg' %}" class="nav-img">
                    <a href="{% url 'Communication:message_read'%}">已读信息</a>
               </div>
                <div class="item">
                    <img src="{% static 'images/icon/write_message.png' %}" class="nav-img">
                   <a href="{% url 'Communication:write_message'%}">写信</a>
               </div>
              <div class="item">
                  <img src="{% static 'images/icon/contact_us.jpg' %}" class="nav-img">
                   <a href="{% url 'Communication:contact_us'%}">反馈</a>
               </div>
            </div>

     <div class="content">
            <div class="panel-heading"style="background-color:#C1C3D1;border-color:white;font-size: 15px">
        已发私信
            </div>

   <table class="table ">
    <thead>
      <tr>
          <th>收件人</th>
       <th>标题</th>
       <th>状态</th>
          <th>发送时间</th>
      </tr>
    </thead>
  <tbody>
  {% for message in good_list %}
     <tr>
      <td>{{ message.message_receiver }}</td>
       <td><a href="{% url 'Communication:message_details' message.message_id%}">{{ message.title }}</a></td>
      {% if message.is_new == '0' %}
       <td>未读</td>
      {% else %}
      <td>已读</td>
      {% endif %}
      <td>{{ message.c_time }}</td>
     {% endfor %}
     </tr>
  </tbody>
</table>


                           <div class="page">
                {% if data %}
                    <ul id="pages" class="pagination pagination-sm pagination-xs">
                        {% if data.first %}
                            <li><a href="?page=1">1</a></li>
                        {% endif %}
                        {% if data.left %}
                            {% if data.left_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                            {% for i in data.left %}
                                <li><a href="?page={{i}}">{{i}}</a></li>
                            {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{data.page}}">{{data.page}}</a></li>
                        {% if data.right %}
                            {% for i in data.right %}
                                <li><a href="?page={{i}}">{{i}}</a></li>
                            {% endfor %}
                            {% if data.right_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                        {% endif %}
                        {% if data.last %}
                            <li><a href="?page={{data.total_pages}}">{{data.total_pages}}</a></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
            </div>






        {% endblock%}

templates/communication/message_read.html
{% extends 'accounts/base.html' %}

{% load staticfiles %}

{% block title %}
已读信息
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">

{% endblock %}

      {% block content %}
<div class="nav1" >

               <div class="item home">
                   <img src="{% static 'images/icon/system_message.jpg' %}" class="nav-img">
                    <a href="{% url 'Communication:system_message' %}">系统通知</a>
               </div>
               <div class="item">
                   <img src="{% static 'images/icon/person_message.jpg' %}" class="nav-img">
                  <a href="{% url 'Communication:person_message' %}"> 收信箱</a>
               </div>
               <div class="item">
                   <img src="{% static 'images/icon/message_by_me.jpg' %}" class="nav-img">
                   <a href="{% url 'Communication:message_by_me' %}">已发私信</a>
               </div>
              <div class="item">
                  <img src="{% static 'images/icon/message_marked.jpg' %}" class="nav-img">
                  <a href="{% url 'Communication:marked_message'%}">特别标注</a>
              </div>
                <div class="item">
                    <img src="{% static 'images/icon/chat.jpg' %}" class="nav-img">
                    <a href="{% url 'Communication:chat'%}">聊天室</a>
               </div>
                <div class="item">
                    <img src="{% static 'images/icon/message_read.jpg' %}" class="nav-img">
                 已读信息
               </div>
                <div class="item">
                    <img src="{% static 'images/icon/write_message.png' %}" class="nav-img">
                   <a href="{% url 'Communication:write_message'%}">写信</a>
               </div>
              <div class="item">
                  <img src="{% static 'images/icon/contact_us.jpg' %}" class="nav-img">
                   <a href="{% url 'Communication:contact_us'%}">反馈</a>
               </div>
            </div>

     <div class="content">
            <div class="panel-heading"style="background-color:#C1C3D1;border-color:white;font-size: 15px">
        已读信息
            </div>
        <form action="/Communication/search_message/" method="post">
            请输入标题进行精准搜索：
            <input type="search" name="title" style="height:30px;width: 400px" placeholder="输入标题">
                        <button type="submit">提交</button>
            {% csrf_token %}
        </form>
   <table class="table ">
    <thead>
      <tr>
       <th>发送人</th>
       <th>标题</th>
          <th>时间</th>
      </tr>
    </thead>
  <tbody>
  {% for message in message %}
     <tr>
       <td>{{ message.message_sender }}</td>
       <td><a href="{% url 'Communication:message_details' message.message_id%}">{{ message.title }}</a></td>
       <td>{{ message.c_time }}</td>
     {% endfor %}

    {% for notice in notice %}
     <tr>
       <td>客服一号</td>
       <td><a href="{% url 'Communication:notice_details' notice.Notice_ID%}">{{ notice.title }}</a></td>
       <td>{{ notice.c_time }}</td>
     {% endfor %}
     </tr>
  </tbody>
</table>

            </div>


        {% endblock%}

templates/communication/person_message.html
{% extends 'accounts/base.html' %}

{% load staticfiles %}

{% block title %}
收件箱
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">

{% endblock %}

    {% block content %}
<div class="nav1">


               <div class="item home">
                   <img src="{% static 'images/icon/system_message.jpg' %}" class="nav-img">
                    <a href="{% url 'Communication:system_message' %}">系统通知</a>
               </div>
               <div class="item">
                   <img src="{% static 'images/icon/person_message.jpg' %}" class="nav-img">
                   收信箱
               </div>
               <div class="item">
                   <img src="{% static 'images/icon/message_by_me.jpg' %}" class="nav-img">
                   <a href="{% url 'Communication:message_by_me'%}">已发私信</a>
               </div>
              <div class="item">
                  <img src="{% static 'images/icon/message_marked.jpg' %}" class="nav-img">
                  <a href="{% url 'Communication:marked_message'%}">特别标注</a>
              </div>
                <div class="item">
                    <img src="{% static 'images/icon/chat.jpg' %}" class="nav-img">
                    <a href="{% url 'Communication:chat'%}">聊天室</a>
               </div>
                <div class="item">
                    <img src="{% static 'images/icon/message_read.jpg' %}" class="nav-img">
                    <a href="{% url 'Communication:message_read'%}">已读信息</a>
               </div>
                <div class="item">
                    <img src="{% static 'images/icon/write_message.png' %}" class="nav-img">
                   <a href="{% url 'Communication:write_message'%}">写信</a>
               </div>
              <div class="item">
                  <img src="{% static 'images/icon/contact_us.jpg' %}" class="nav-img">
                   <a href="{% url 'Communication:contact_us'%}">反馈</a>
               </div>
            </div>

     <div class="content">
            <div class="panel-heading"style="background-color:#C1C3D1;border-color:white;font-size: 15px">
        收件箱
            </div>
   <table class="table ">
    <thead>
      <tr>
       <th>发送人</th>
       <th>标题</th>
          <th>发送时间</th>
           <th>标记</th>
      </tr>
    </thead>
  <tbody>
  {% for message in good_list %}
     <tr>
       <td>{{ message.message_sender }}</td>
       <td><a href="{% url 'Communication:message_details' message.message_id%}">{{ message.title }}</a></td>
      <td>{{ message.c_time }}</td>
     <td> <a href="{% url 'Communication:mark_by_receiver' message.message_id%}">标记</a></td>
     {% endfor %}
     </tr>
  </tbody>
</table>

                                <div class="page">
                {% if data %}
                    <ul id="pages" class="pagination pagination-sm pagination-xs">
                        {% if data.first %}
                            <li><a href="?page=1">1</a></li>
                        {% endif %}
                        {% if data.left %}
                            {% if data.left_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                            {% for i in data.left %}
                                <li><a href="?page={{i}}">{{i}}</a></li>
                            {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{data.page}}">{{data.page}}</a></li>
                        {% if data.right %}
                            {% for i in data.right %}
                                <li><a href="?page={{i}}">{{i}}</a></li>
                            {% endfor %}
                            {% if data.right_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                        {% endif %}
                        {% if data.last %}
                            <li><a href="?page={{data.total_pages}}">{{data.total_pages}}</a></li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>

            </div>



        {% endblock%}