Send/urls.py
from django.conf.urls import url
from .import views
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

app_name = 'Send'
urlpatterns = [


    url(r'^send_category', views.send_category, name='send_category'),
    url(r'^add_order', views.add_order, name='add_order'),
    url(r'^filling_suc', views.filling_suc, name='filling_suc'),
    url(r'^(?P<task_id>[0-9]+)/send_details/$', views.send_details, name='send_details'),
    url(r'^(?P<task_id>[0-9]+)/reset/', views.reset, name='reset'),

    url(r'^recommend_master', views.recommend_master, name='recommend_master'),
    url(r'^popular_master', views.popular_master, name='popular_master'),
    url(r'^(?P<master_type_id>[0-9]+)/masters_category/$', views.master_category, name='master_category'),
    url(r'^masters', views.masters, name='masters'),
    url(r'^(?P<master_id>[0-9]+)/master_details/$', views.master_details, name='master_details'),
    url(r'^(?P<master_id>[0-9]+)/add_order_of_master/$', views.add_order_of_master, name='add_order_of_master'),
    url(r'^master_like', views.master_like, name='master_like'),
    url(r'^master_favorite$', views.master_favorite, name='master_favorite'),
    url(r'^(?P<task_id>[0-9]+)/del_send_suc$', views.del_send_suc, name='del_send_suc'),

    url(r'^recommend_good', views.recommend_good, name='recommend_good'),
    url(r'^popular_good', views.popular_good, name='popular_good'),
    url(r'^(?P<good_type_id>[0-9]+)/good_category/$', views.good_category, name='good_category'),
    url(r'^goods', views.goods, name='goods'),
    url(r'^(?P<good_id>[0-9]+)/good_details/$', views.good_details, name='good_details'),
    url(r'^good_favorite/$', views.good_favorite, name='good_favorite'),
    url(r'^add_car', views.add_car, name='add_car'),

    url(r'^add_competition', views.add_competition, name='add_competition'),
    url(r'^suc', views.suc, name='suc'),
    url(r'^reset', views.reset, name='reset'),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

WeHelp20/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.urls import path
from Login import views
from django.views.static import serve
from django.conf.urls.static import static
from Communication import views as uv
from Boards import views as boards_views
from django.contrib.auth import views as auth_views
from Login.views import ForgetPwdView, ResetView,  ModifyPwdView
from django.urls import re_path
from django.views.generic.base import RedirectView
from Send import views as sd
from Take import views as tk

urlpatterns = [
    url(r'^$', views.wehelp, name='wehelp'),
    url(r'^wehelp', views.wehelp, name='wehelp'),
    url('about_platform/', views.about_platform, name='about_platform'),
    url(r'^Send/', include('Send.urls')),
    url(r'^is_login', sd.is_login, name='is_login'),
    url(r'^Take/', include('Take.urls')),
    url(r'^admin/', admin.site.urls),
    url('register/', views.RegisterView.as_view()),
    path('login/', views.LoginView.as_view(),name='login'),
    path('logout/', views.logout_view),
    path('reset_pw/', views.reset_pw),
    path('tags/', views.tags),
    path('tags/new/', views.new_tags),
    path('send/', views.get_orders),
    path('task/', views.get_tasks),
    path('new_avatar/', views.new_avatar, name='new_avatar'),
    path('index/', views.index),
    path('collection/', views.get_collection),
    path('goodfavorite/', views.good_favorite),
    path('collection_c/', views.collection_c),
    path('disclamier/', views.disclaimer),
    path('map/', views.map),
    path('bar/', views.bar),
    path('doughnut/', views.doughnut),
    path('line/', views.line),
    path('linecus/', views.linecus),
    path('pie/', views.pie),
    path('piecus/', views.piecus),
    path('polar/', views.polar),
    path('radar/', views.radar),

    # 验证码以邮箱找回密码
    path("forget/", ForgetPwdView.as_view(), name="forget_pwd"),
    path("captcha/", include('captcha.urls')),
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name="reset_pwd"),
    path("modify/", ModifyPwdView.as_view(), name="modify_pwd"),

    url(r'^Communication/', include('Communication.urls')),

    url(r'^chat/', include('chat.urls')),

    url(r'^about_platform',uv.about_platform, name='about_platform'),
    url(r'^about_us/$', tk.about_us, name='about_us'),

    #url(r'^search',uv.search,name='search'),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^luntan/$', boards_views.BoardListView.as_view(), name='luntan'),
    url(r'^search_subject/$', boards_views.search_subject, name='search_subject'),
    url(r'^boards/(?P<pk>\d+)/$', boards_views.TopicListView.as_view(), name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', boards_views.new_topic, name='new_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', boards_views.PostListView.as_view(),
                      name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', boards_views.reply_topic, name='reply_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/complain/$', boards_views.complain, name='complain'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/luntanuser/$', boards_views.luntanuser,name='luntanuser'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
                      boards_views.PostUpdateView.as_view(), name='edit_post'),
    url(r'^edit_post2/$', boards_views.edit_post2, name="edit_post2"),
    url(r'^new_topic2/$', boards_views.new_topic2, name='new_topic2'),
    url(r'^complain2/$', boards_views.complain2, name="complain2"),
    url(r'^delete/$', boards_views.delete2, name='delete2'),
    url(r'^contact_us/$', boards_views.contact_us, name='contact_us'),
    url(r'^contact_way/$', boards_views.contact_way, name="contact_way"),
    url(r'^cooperation/$', boards_views.cooperation, name="cooperation"),
    url(r'^joinus/$', boards_views.joinus, name="joinus"),
    url(r'^boards/(?P<pk>\d+)/top/$', boards_views.top, name='top'),

    # 添加网站小图标
     url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Send/models.py
from django.db import models
from Login.models import User, MasterType, TaskSend, MasterLike, MasterFavorite, GoodType, Good, GoodCar,GoodFavorite, TaskTake, Collection, Competition, Message, suggestion, Board, Topic, Post, Report


# Create your models here.

Login/views.py


# Create your views here.
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth import login, logout
from django.contrib.auth import get_user_model
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import MasterType, GoodFavorite
from .models import TaskSend, TaskTake, User,Notice
from .forms import RegisterForm, LoginForm, ResetPWForm, TagForm,ResetPWForm, ModifyPwdForm, ForgetForm
from .models import Collection,CollectionCompetition
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import EmailVerifyRecord
from django.contrib.auth.hashers import make_password
from utils.email_send import send_register_email


User = get_user_model()


class RegisterView(View):
    """
    注册视图
    """
    def get(self, request):
        logout(request)
        return render(request, 'accounts/register.html')

    def post(self, request):
        logout(request)
        form = RegisterForm(request.POST)
        if form.is_valid():
            new_user = User(**form.cleaned_data)
            # hash密码
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()
            username=new_user.username
            Notice.objects.create(title='欢迎使用WeHelp!',
                                  message_fromsystem='欢迎使用WeHelp!',
                                  message_receiver= username
                                  )
            login(request, new_user)
            return redirect('/login/')

        return render(request, 'accounts/register.html', {'form': form})


class LoginView(View):
    """
    登录视图
    """
    def get(self, request):
        logout(request)
        return render(request, 'accounts/login.html')

    def post(self, request):
        logout(request)
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = User.objects.filter(username=username).first()
            # 验证密码
            if user.check_password(password):
                login(request, user)
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['username'] = user.username
                user.is_login = 1
                user.save()
                return redirect('/')
        error_message='请输入正确的用户名和密码'
        return render(request, 'accounts/login.html', {'error_message':error_message,})


@login_required(login_url='/login/')
def logout_view(request):
    """
    注销登录视图
    """
    user_id = request.session['user_id']
    user = User.objects.get(id=user_id)
    user.is_login = 0
    user.save()
    logout(request)
    return redirect('/')


def success_response(message):
    data = {}
    data['status'] = 'SUCCESS'
    data['message'] = message
    return JsonResponse(data)


@login_required(login_url='/login/')
def index(request):
    """
    主页视图
    """
    user = request.user
    if request.method == 'POST':
        user.name = request.POST.get('name')
        user.college = request.POST.get('college')
        user.major = request.POST.get('major')
        user.birthday = request.POST.get('birthday')
        user.email = request.POST.get('email')
        user.qq_num = request.POST.get('qq_num')
        user.save()

    return render(request, 'accounts/index.html', {'user': request.user})


@login_required(login_url='/login/')
def reset_pw(request):
    """
    修改密码视图
    """
    form = ResetPWForm(request.POST)
    if form.is_valid():
        user = User.objects.filter(id=request.user.id).first()
        if user and user.check_password(form.cleaned_data['password1']):
            user.set_password(form.cleaned_data['password2'])
            user.save()
            return render(request, 'accounts/reset_pw.html', {'message': '修改密码成功!'})

    return render(request, 'accounts/reset_pw.html')


@login_required(login_url='/login/')
def get_orders(request):
    """
    已发订单视图
    """
    user_id = request.session['user_id']
    orders = TaskSend.objects.all().filter(sender__id=user_id)
    p = Paginator(orders, 14)  # 分页，10篇文章一页
    if p.num_pages <= 1:  # 如果文章不足一页
        order_list = orders  # 直接返回所有文章
        data = ''  # 不需要分页按钮
    else:
        page = int(request.GET.get('page', 1))  # 获取请求的文章页码，默认为第一页
        order_list = p.page(page)  # 返回指定页码的页面
        left = []  # 当前页左边连续的页码号，初始值为空
        right = []  # 当前页右边连续的页码号，初始值为空
        left_has_more = False  # 标示第 1 页页码后是否需要显示省略号
        right_has_more = False  # 标示最后一页页码前是否需要显示省略号
        first = False  # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        # 初始值为 False
        last = False  # 标示是否需要显示最后一页的页码号。
        total_pages = p.num_pages
        page_range = p.page_range
        if page == 1:  # 如果请求第1页
            right = page_range[page:page + 2]  # 获取右边连续号码页
            if right[-1] < total_pages - 1:  # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
                # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
                right_has_more = True
            if right[-1] < total_pages:  # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码
                # 所以需要显示最后一页的页码号，通过 last 来指示
                last = True
        elif page == total_pages:  # 如果请求最后一页
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]  # 获取左边连续号码页
            if left[0] > 2:
                left_has_more = True  # 如果最左边的号码比2还要大，说明其与第一页之间还有其他页码，因此需要显示省略号，通过 left_has_more 来指示
            if left[0] > 1:  # 如果最左边的页码比1要大，则要显示第一页，否则第一页已经被包含在其中
                first = True
        else:  # 如果请求的页码既不是第一页也不是最后一页
            left = page_range[(page - 3) if (page - 3) > 0 else 0:page - 1]  # 获取左边连续号码页
            right = page_range[page:page + 2]  # 获取右边连续号码页
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
        data = {  # 将数据包含在data字典中
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
            'total_pages': total_pages,
            'page': page
        }
    return render(request, 'accounts/send.html', context={'orders': order_list, 'data': data})


@login_required(login_url='/login/')
def get_tasks(request):
    """
    已接订单视图
    """
    user_id = request.session['user_id']
    tasks = TaskTake.objects.all().filter(task_taker_id__id=user_id)
    return render(request, 'accounts/task.html', {'tasks': tasks})


@login_required(login_url='/login/')
def tags(request):
    """
    标签视图
    """
    tags = MasterType.objects.all().order_by('master_type_name')
    return render(request, 'accounts/tags.html', {'tags': tags})


@login_required(login_url='/login/')
def new_tags(request):
    """
    添加标签视图
    """
    if request.method == "POST":
        user_id = request.session['user_id']
        user = User.objects.get(id=user_id)
        master_type_id = request.POST.get('master_type_id')
        user.master_type_id = master_type_id
        user.save()
        type = user.master_type
        return render(request, 'accounts/new_tags.html', {'type': type})
    return render(request, 'accounts/new_tags.html')


@login_required(login_url='/login/')
def new_avatar(request):
    """
    用户头像
    """
    if request.method == 'POST' and request.FILES['avatar']:
        user_id = request.session['user_id']
        user = User.objects.get(id=user_id)
        user.avatar = request.FILES.get('avatar')
        user.save()
        return redirect('/index')
    return redirect('/index')



@login_required(login_url='/login/')
def get_collection(request):
    """
    我的收藏视图
    """
    user_id = request.session['user_id']
    collection = Collection.objects.all().filter(collection_collector_id__id=user_id)
    return render(request, 'accounts/collection.html', {'collections': collection})


@login_required(login_url='/login/')
def good_favorite(request):
    """
    我的收藏商品视图
    """
    user_id = request.session['user_id']
    goodfavorite = GoodFavorite.objects.all().filter(user__id=user_id)
    return render(request, 'accounts/goodfavorite.html', {'goodfavorite': goodfavorite})


def wehelp(request):
    pass
    return render(request, 'wehelp.html')


def about_platform(request):
    pass
    return render(request, 'about_platform.html')


class ForgetPwdView(View):
    def get(self, request):
        forget_form = ForgetForm()
        return render(request, 'login/forgetpwd.html', {'forget_form': forget_form})

    def post(self, request):
        forget_form = ForgetForm(request.POST)
        if forget_form.is_valid():
            email = request.POST.get('email', '')
            # 发送找回密码的邮件
            send_register_email(email, 'forget')
            return render(request, 'login/send_success.html')
        else:
            return render(request, "login/forgetpwd.html", {'forget_form': forget_form})


class ResetView(View):
    def get(self, request, active_code):
        # 用于查询邮箱验证码是否存在
        all_record = EmailVerifyRecord.objects.filter(code=active_code)
        if all_record:
            for record in all_record:
                # 获取到对应的邮箱
                email = record.email
                # 查找到邮箱对应的用户

templates/accounts/collection.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}
<div class="nav1">
  <div class="item home">
      <img src="{% static 'images/icon/icon01.jpg' %}" class="nav-img">
    <a href="/index/">个人资料</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon02.png' %}" class="nav-img">
    <a href="/reset_pw/">修改密码</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon03.jpg' %}" class="nav-img">
    <a href="/send/">已发订单</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon04.png' %}" class="nav-img">
    <a href="/task/">已接订单</a>
  </div>
        <div class="item">
            <img src="{% static 'images/icon/icon05.jpg' %}" class="nav-img">
      <a href="/collection/">我收藏的订单</a>
  </div>
       <div class="item">
           <img src="{% static 'images/icon/icon06.jpg' %}" class="nav-img">
      <a href="/goodfavorite/">我收藏的商品</a>
  </div>
     <div class="item">
         <img src="{% static 'images/icon/icon07.jpg' %}" class="nav-img">
      <a href="/collection_c/">我收藏的大赛</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon08.png' %}" class="nav-img">
    <a href="/tags/">达人认证</a>
  </div>

  <div class="item">
      <img src="{% static 'images/icon/icon09.png' %}" class="nav-img">
    <a href="/logout/">注销登录</a>
  </div>
</div>
 <div class="content">
  <table>
    <tr>
      <th>收藏ID</th>
      <th>收藏者</th>
      <th>收藏的订单</th>
      <th>收藏时间</th>
    </tr>

      {% for collection in collections %}
          <tr>
      <td>{{ collection.collection_id }}</td>
      <td>{{ collection.collection_collector_id }}</td>
      <td>{{ collection.collection_thing_id }}</td>
      <td>{{ collection.collection_time }}</td>
          </tr>
      {% endfor %}
  </table>
</div>



<script>
$(function() {
  if ((location.pathname.split("/")[1]) !== ""){
    $('nav a[href^="/' + location.pathname.split("/")[1] + '"]').parent(".item").addClass('active');
  } else {
    $('.home').addClass('active');
  }
});
</script>
{% endblock %}

templates/accounts/send.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/sd.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/index02.css' %}">

{% endblock %}


{% block content %}
<div class="nav1">
  <div class="item home">
      <img src="{% static 'images/icon/icon01.jpg' %}" class="nav-img">
    <a href="/index/">个人资料</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon02.png' %}" class="nav-img">
    <a href="/reset_pw/">修改密码</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon03.jpg' %}" class="nav-img">
    <a href="/send/">已发订单</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon04.png' %}" class="nav-img">
    <a href="/task/">已接订单</a>
  </div>
        <div class="item">
            <img src="{% static 'images/icon/icon05.jpg' %}" class="nav-img">
      <a href="/collection/">我收藏的订单</a>
  </div>
       <div class="item">
           <img src="{% static 'images/icon/icon06.jpg' %}" class="nav-img">
      <a href="/goodfavorite/">我收藏的商品</a>
  </div>
     <div class="item">
         <img src="{% static 'images/icon/icon07.jpg' %}" class="nav-img">
      <a href="/collection_c/">我收藏的大赛</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon08.png' %}" class="nav-img">
    <a href="/tags/">达人认证</a>
  </div>

  <div class="item">
      <img src="{% static 'images/icon/icon09.png' %}" class="nav-img">
    <a href="/logout/">注销登录</a>
  </div>
</div>
<div class="content">
      <div class="main-cont main-user">
      {% if orders %}
              <ul class="main-cont__list clearfix">
                  {% for tasksend in orders %}
                      <li class="item">
                          <a href="{% url 'Send:send_details' tasksend.task_id %}" ><img src="/media/{{ tasksend.task_img }}" style="height: 112px;width: 100%;" ></a>
                          <a href="{% url 'Send:send_details' tasksend.task_id %}" class="headImg"><img src="/media/{{ tasksend.task_img }}" alt="#"></a>
                          <div class="info">
                              <a href="{% url 'Send:send_details' tasksend.task_id %}" class="info-title"></a>
                              <p>订单ID： <b>{{ tasksend.task_id}}</b></p>
                          </div>
                      </li>
                  {% endfor %}
              </ul>
      {% else %}
          <div class="res">
          <span>您还没有发布过任何订单哦 </span>
          </div>
      {% endif %}
      </div>
            <div class="page">
                {% if data %}
                    <ul id="pages" class="pagination pagination-sm pagination-xs">
                        {% if data.first %}
                            <li><a href="?page=1">1</a>
                        {% endif %}
                        {% if data.left %}
                            {% if data.left_has_more %}
                                <li><span>...</span>
                            {% endif %}
                            {% for i in data.left %}
                                <li><a href="?page={{i}}">{{i}}</a>
                            {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{data.page}}">{{data.page}}</a>
                        {% if data.right %}
                            {% for i in data.right %}
                                <li><a href="?page={{i}}">{{i}}</a>
                            {% endfor %}
                            {% if data.right_has_more %}
                                <li><span>...</span>
                            {% endif %}
                        {% endif %}
                        {% if data.last %}
                            <li><a href="?page={{data.total_pages}}">{{data.total_pages}}</a>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
</div>



<script>
$(function() {
  if ((location.pathname.split("/")[1]) !== ""){
    $('nav a[href^="/' + location.pathname.split("/")[1] + '"]').parent(".item").addClass('active');
  } else {
    $('.home').addClass('active');
  }
});
</script>
{% endblock %}

templates/accounts/task.html
{% extends 'accounts/base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/sd.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/index02.css' %}">

{% endblock %}


{% block content %}
<div class="nav1">
  <div class="item home">
      <img src="{% static 'images/icon/icon01.jpg' %}" class="nav-img">
    <a href="/index/">个人资料</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon02.png' %}" class="nav-img">
    <a href="/reset_pw/">修改密码</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon03.jpg' %}" class="nav-img">
    <a href="/send/">已发订单</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon04.png' %}" class="nav-img">
    <a href="/task/">已接订单</a>
  </div>
        <div class="item">
            <img src="{% static 'images/icon/icon05.jpg' %}" class="nav-img">
      <a href="/collection/">我收藏的订单</a>
  </div>
       <div class="item">
           <img src="{% static 'images/icon/icon06.jpg' %}" class="nav-img">
      <a href="/goodfavorite/">我收藏的商品</a>
  </div>
     <div class="item">
         <img src="{% static 'images/icon/icon07.jpg' %}" class="nav-img">
      <a href="/collection_c/">我收藏的大赛</a>
  </div>
  <div class="item">
      <img src="{% static 'images/icon/icon08.png' %}" class="nav-img">
    <a href="/tags/">达人认证</a>
  </div>

  <div class="item">
      <img src="{% static 'images/icon/icon09.png' %}" class="nav-img">
    <a href="/logout/">注销登录</a>
  </div>
</div>
<div class="content">
      <div class="main-cont main-user">
      {% if tasks %}
              <ul class="main-cont__list clearfix">
                  {% for task in tasks %}
                      <li class="item">
                          <a href="{% url 'Send:send_details' user.id %}" ><img src="/media/{{ task.task_send_id.task_img }}" style="height: 112px;width: 100%;" ></a>
                          <a href="{% url 'Send:send_details' user.id %}" class="headImg"><img src="/media/{{ task.task_send_id.task_img }}" alt="#"></a>
                          <div class="info">
                              <a href="{% url 'Send:send_details' user.id %}" class="info-title"></a>
                              <p>订单ID： <b>{{ task.task_take_id}}</b></p>
                          </div>
                      </li>
                  {% endfor %}
              </ul>
      {% else %}
          <div class="res">
          <span>您还没有接过任何订单哦 </span>
          </div>
      {% endif %}
      </div>
            <div class="page">
                {% if data %}
                    <ul id="pages" class="pagination pagination-sm pagination-xs">
                        {% if data.first %}
                            <li><a href="?page=1">1</a>
                        {% endif %}
                        {% if data.left %}
                            {% if data.left_has_more %}
                                <li><span>...</span>
                            {% endif %}
                            {% for i in data.left %}
                                <li><a href="?page={{i}}">{{i}}</a>
                            {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{data.page}}">{{data.page}}</a>
                        {% if data.right %}
                            {% for i in data.right %}
                                <li><a href="?page={{i}}">{{i}}</a>
                            {% endfor %}
                            {% if data.right_has_more %}
                                <li><span>...</span>
                            {% endif %}
                        {% endif %}
                        {% if data.last %}
                            <li><a href="?page={{data.total_pages}}">{{data.total_pages}}</a>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
 <div class="page">
                {% if data %}
                    <ul id="pages" class="pagination pagination-sm pagination-xs">
                        {% if data.first %}
                            <li><a href="?page=1">1</a>
                        {% endif %}
                        {% if data.left %}
                            {% if data.left_has_more %}
                                <li><span>...</span>
                            {% endif %}
                            {% for i in data.left %}
                                <li><a href="?page={{i}}">{{i}}</a>
                            {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{data.page}}">{{data.page}}</a>
                        {% if data.right %}
                            {% for i in data.right %}
                                <li><a href="?page={{i}}">{{i}}</a>
                            {% endfor %}
                            {% if data.right_has_more %}
                                <li><span>...</span>
                            {% endif %}
                        {% endif %}
                        {% if data.last %}
                            <li><a href="?page={{data.total_pages}}">{{data.total_pages}}</a>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
</div>



<script>
$(function() {
  if ((location.pathname.split("/")[1]) !== ""){
    $('nav a[href^="/' + location.pathname.split("/")[1] + '"]').parent(".item").addClass('active');
  } else {
    $('.home').addClass('active');
  }
});
</script>
{% endblock %}