Send/urls.py
from django.conf.urls import url
from .import views
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static

app_name = 'Send'
urlpatterns = [


    url(r'^send_category', views.send_category, name='send_category'),
    url(r'^add_order', views.add_order, name='add_order'),
    url(r'^filling_suc', views.filling_suc, name='filling_suc'),
    url(r'^(?P<task_id>[0-9]+)/send_details/$', views.send_details, name='send_details'),
    url(r'^(?P<task_id>[0-9]+)/reset/', views.reset, name='reset'),

    url(r'^recommend_master', views.recommend_master, name='recommend_master'),
    url(r'^popular_master', views.popular_master, name='popular_master'),
    url(r'^(?P<master_type_id>[0-9]+)/masters_category/$', views.master_category, name='master_category'),
    url(r'^masters', views.masters, name='masters'),
    url(r'^(?P<master_id>[0-9]+)/master_details/$', views.master_details, name='master_details'),
    url(r'^(?P<master_id>[0-9]+)/add_order_of_master/$', views.add_order_of_master, name='add_order_of_master'),
    url(r'^master_like', views.master_like, name='master_like'),
    url(r'^master_favorite$', views.master_favorite, name='master_favorite'),
    url(r'^(?P<task_id>[0-9]+)/del_send_suc$', views.del_send_suc, name='del_send_suc'),

    url(r'^recommend_good', views.recommend_good, name='recommend_good'),
    url(r'^popular_good', views.popular_good, name='popular_good'),
    url(r'^(?P<good_type_id>[0-9]+)/good_category/$', views.good_category, name='good_category'),
    url(r'^goods', views.goods, name='goods'),
    url(r'^(?P<good_id>[0-9]+)/good_details/$', views.good_details, name='good_details'),
    url(r'^good_favorite/$', views.good_favorite, name='good_favorite'),
    url(r'^add_car', views.add_car, name='add_car'),

    url(r'^add_competition', views.add_competition, name='add_competition'),
    url(r'^suc', views.suc, name='suc'),
    url(r'^reset', views.reset, name='reset'),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Take/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib import admin
from Take import views
from django.conf.urls.static import static
from django.conf import settings
from django.urls import re_path

app_name = 'Take'
urlpatterns = [
    url(r'^task_take/$', views.task_take, name='task_take'),#接单首页的细分类
    url(r'^task_take_division/(?P<task_category>\w+)/$', views.task_take_division, name='task_take_division'),#接单首页的细分类
    url(r'^task_take_division_hot/$', views.task_take_division_hot, name='task_take_division_hot'),#接单首页的热门任务
    url(r'^task_take_division_all/$', views.task_take_division_all, name='task_take_division_all'),#接单首页的所有任务
    url(r'^task_sender_details/(?P<sender_id>\d+)/sender/(?P<task_id>\d+)/$', views.task_sender_details, name='task_sender_details'),#接单首页的所有任务
    url(r'^task_take_division/(?P<task_id>\d+)/fresh/$', views.task_take_division_details, name='task_take_division_details'),#实时更新任务的详情url
    url(r'^task_take_success/(?P<task_id>\d+)/$', views.task_take_success, name='task_take_success'),
    url(r'^task_take_division/Take/task_take_goods/', views.task_take_goods, name='task_take_goods'),
    url(r'^task_take_delete/(?P<good_id>\d+)/$', views.task_take_delete, name='task_take_delete'),

    url(r'^task_take_recommend/', views.task_take_recommend, name='task_take_recommend'),

    url(r'^task_take_tips/', views.task_take_tips, name='task_take_tips'),

    url(r'^task_take_goods/', views.task_take_goods, name='task_take_goods'),
    url(r'^task_take_goods_success/', views.task_take_goods_success, name='task_take_goods_success'),


    url(r'^task_take_competition/$', views.task_take_competition, name='task_take_competition'),
    url(r'^task_take_competition_hot/$', views.task_take_competition_hot, name='task_take_competition_hot'),
    url(r'^task_take_competition/(?P<competition_id>\d+)/$', views.task_take_competition_details, name='task_take_competition_details'),
    url(r'^task_take_competition_collection/$', views.task_take_competition_collection, name='task_take_competition_collection'),

    url(r'^task_take_collection/$', views.task_take_collection, name='task_take_collection'),

    url(r'^task_take_example/$', views.task_take_example, name='task_take_example'),
    url(r'^about_us/$', views.about_us, name='about_us'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

WeHelp20/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.urls import path
from Login import views
from django.views.static import serve
from django.conf.urls.static import static
from Communication import views as uv
from Boards import views as boards_views
from django.contrib.auth import views as auth_views
from Login.views import ForgetPwdView, ResetView,  ModifyPwdView
from django.urls import re_path
from django.views.generic.base import RedirectView
from Send import views as sd
from Take import views as tk

urlpatterns = [
    url(r'^$', views.wehelp, name='wehelp'),
    url(r'^wehelp', views.wehelp, name='wehelp'),
    url('about_platform/', views.about_platform, name='about_platform'),
    url(r'^Send/', include('Send.urls')),
    url(r'^is_login', sd.is_login, name='is_login'),
    url(r'^Take/', include('Take.urls')),
    url(r'^admin/', admin.site.urls),
    url('register/', views.RegisterView.as_view()),
    path('login/', views.LoginView.as_view(),name='login'),
    path('logout/', views.logout_view),
    path('reset_pw/', views.reset_pw),
    path('tags/', views.tags),
    path('tags/new/', views.new_tags),
    path('send/', views.get_orders),
    path('task/', views.get_tasks),
    path('new_avatar/', views.new_avatar, name='new_avatar'),
    path('index/', views.index),
    path('collection/', views.get_collection),
    path('goodfavorite/', views.good_favorite),
    path('collection_c/', views.collection_c),
    path('disclamier/', views.disclaimer),
    path('map/', views.map),
    path('bar/', views.bar),
    path('doughnut/', views.doughnut),
    path('line/', views.line),
    path('linecus/', views.linecus),
    path('pie/', views.pie),
    path('piecus/', views.piecus),
    path('polar/', views.polar),
    path('radar/', views.radar),

    # 验证码以邮箱找回密码
    path("forget/", ForgetPwdView.as_view(), name="forget_pwd"),
    path("captcha/", include('captcha.urls')),
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name="reset_pwd"),
    path("modify/", ModifyPwdView.as_view(), name="modify_pwd"),

    url(r'^Communication/', include('Communication.urls')),

    url(r'^chat/', include('chat.urls')),

    url(r'^about_platform',uv.about_platform, name='about_platform'),
    url(r'^about_us/$', tk.about_us, name='about_us'),

    #url(r'^search',uv.search,name='search'),

    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),

    url(r'^luntan/$', boards_views.BoardListView.as_view(), name='luntan'),
    url(r'^search_subject/$', boards_views.search_subject, name='search_subject'),
    url(r'^boards/(?P<pk>\d+)/$', boards_views.TopicListView.as_view(), name='board_topics'),
    url(r'^boards/(?P<pk>\d+)/new/$', boards_views.new_topic, name='new_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', boards_views.PostListView.as_view(),
                      name='topic_posts'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', boards_views.reply_topic, name='reply_topic'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/complain/$', boards_views.complain, name='complain'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/luntanuser/$', boards_views.luntanuser,name='luntanuser'),
    url(r'^boards/(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts/(?P<post_pk>\d+)/edit/$',
                      boards_views.PostUpdateView.as_view(), name='edit_post'),
    url(r'^edit_post2/$', boards_views.edit_post2, name="edit_post2"),
    url(r'^new_topic2/$', boards_views.new_topic2, name='new_topic2'),
    url(r'^complain2/$', boards_views.complain2, name="complain2"),
    url(r'^delete/$', boards_views.delete2, name='delete2'),
    url(r'^contact_us/$', boards_views.contact_us, name='contact_us'),
    url(r'^contact_way/$', boards_views.contact_way, name="contact_way"),
    url(r'^cooperation/$', boards_views.cooperation, name="cooperation"),
    url(r'^joinus/$', boards_views.joinus, name="joinus"),
    url(r'^boards/(?P<pk>\d+)/top/$', boards_views.top, name='top'),

    # 添加网站小图标
     url(r'^favicon.ico$', RedirectView.as_view(url=r'static/favicon.ico')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Take/models.py
from django.db import models

# Create your models here.

Take/templates/task_take.html
{% extends 'home.html' %}
{% load static %}
{% block title %}接任务 {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/sd_cate.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/index02.css' %}" type = "text/css"/>
{% endblock %}

{% block content %}
  <div class="main">
      <div class="main-inner body-width">
          <div class="banner clearfix" >
              <div class="banner-info" >
                  <div style=" margin-left: 20px;margin-right: 124px">
                      <div class="news body-border">
                          <ul >
                          <li class="rec" style="background: url({% static 'images/dm01.png'%}) no-repeat; border: #bcade4 1px solid">
                              <a href="{% url 'Take:task_take_recommend' %}"> <b><u>推荐接单</u></b></a>
                          </li>
                          <li class="pop" style="background: url({% static 'images/dm02.png'%}) no-repeat right; border: #bcade4 1px solid">
                              <a href="{% url 'Take:task_take_competition' %}"><b><u>参加大赛</u></b></a>
                          </li>
                          <li class="all" style="background: url({% static 'images/dm01.png'%}) no-repeat left; border: #bcade4 1px solid">
                              <a href="{% url 'Take:task_take_tips' %}"><b><u>接单说明</u></b></a>
                          </li>
                          </ul>
                       </div>
                  </div>
              </div>
              <div class="banner-info">
                  <div class="news body-border">
                      <ul >
                          <li class="rec" style="background: url({% static 'images/dm01.png'%}) no-repeat; border: #bcade4 1px solid">
                              <a href="{% url 'Take:task_take_division_all' %}"> <b><u>普通接单</u></b></a>
                          </li>
                          <li class="pop" style="background: url({% static 'images/dm02.png'%}) no-repeat right; border: #bcade4 1px solid">
                              <a href="{% url 'Take:task_take_goods' %}"><b><u>上传商品</u></b></a>
                          </li>
                          <li class="all" style="background: url({% static 'images/dm01.png'%}) no-repeat left; border: #bcade4 1px solid">
                              <a href="{% url 'Take:task_take_example' %}"><b><u>接单案例</u></b></a>
                          </li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}

Take/templates/task_take_competition.html
{% extends 'home.html' %}
{% load static %}
{% block title %}大赛中心{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/rec_gd.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/index02.css' %}" type = "text/css"/>
{% endblock %}

{% block content %}
  <div class="main">
      <div class="main-inner body-width">
          <span class="aa"><a href="{% url 'Take:task_take' %}" class="cate"><<返回接单首页</a></span>
          <div class="banner clearfix" style="height:30%;margin-bottom: 30px">
              <div class="main-cont main-cate">
                  <ul class="main-cont__list clearfix">
                      <li class="item" style=" background: url({% static 'images/dm22.png' %}) no-repeat right; background-size: cover;margin-right: 110px;margin-left: 100px">
                          <div class="info" >
                              <a href="{% url 'Take:task_take_competition_hot' %}" class="info-title"><p><b>热&nbsp;门</b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/dm23.png' %}) no-repeat scroll left; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_competition' %}" class="info-title"><p><b><u>所&nbsp;有</u></b></p></a>
                          </div>
                      </li>
                  </ul>
              </div>
          </div>
          <div class="main-cont main-recommend">
              <div style="margin: 0px auto;text-align: center;width: 100%;" class= "main-cont__title" >
                  <h3 style="font-size: 30px;font-weight: 700;">所&nbsp;有&nbsp;大&nbsp;赛</h3>
                  <p class="list">
              </div>
              <ul class="main-cont__list clearfix">
                  {% if competitions %}
                      {% for competition in competitions %}
                          <li class="item">
                              <img src="/media/{{ competition.competition_poster }}" alt="#" class="img">
                              <div class="info">
                                  <a href="{% url 'Take:task_take_competition_details' competition.competition_id %}" class="title">{{ competition.competition_title}}</a>
                                  <span><span class="pp">❤</span> {{ competition.competition_colletion_times}}&nbsp;&nbsp;&nbsp;</span>
                                  <a href="{% url 'Take:task_take_competition_details' competition.competition_id %}" class="icon-text__pink purchase">详情</a>
                              </div>
                          </li>
                      {% endfor %}
                  {% else %}
                      <h6>当前还没有大赛！</h6>
                  {% endif %}
              </ul>
          </div>
      </div>
      <div class="page" style="width: 20%; margin: 0px auto;">
             {% if data %}
                 <ul id="pages" class="pagination pagination-sm pagination-xs">
                     {% if data.first %}
                         <li><a href="?page=1">1</a></li>
                     {% endif %}
                     {% if data.left %}
                         {% if data.left_has_more %}
                             <li><span>...</span></li>
                         {% endif %}
                         {% for i in data.left %}
                             <li><a href="?page={{i}}">{{i}}</a></li>
                         {% endfor %}
                        {% endif %}
                        <li class="active"><a href="?page={{data.page}}">{{data.page}}</a></li>
                        {% if data.right %}
                            {% for i in data.right %}
                                <li><a href="?page={{i}}">{{i}}</a></li>
                            {% endfor %}
                            {% if data.right_has_more %}
                                <li><span>...</span></li>
                            {% endif %}
                        {% endif %}
                        {% if data.last %}
                            <li><a href="?page={{data.total_pages}}">{{data.total_pages}}</a></li>
                        {% endif %}
                    </ul>
             {% endif %}
         </div>
  </div>
{% endblock %}


Take/templates/task_take_division.html
{% extends 'home.html' %}
{% load static %}
{% block title %}任务细分 {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/rec_gd.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/index02.css' %}" type = "text/css"/>
{% endblock %}

{% block content %}
  <div class="main">
      <div class="main-inner body-width">
      <span class="aa"><a href="{% url 'Take:task_take' %}" class="cate"><<返回接单首页</a></span>
          <div class="banner clearfix">
              <div class="main-cont main-cate" style="width: 89%;margin: 0px auto" >
                  <ul class="main-cont__list clearfix">
                      <li class="item" style=" background: url({% static 'images/dm22.png' %}) no-repeat right; background-size: cover;margin-right: 110px;margin-left: 100px">
                          <div class="info" >
                              <a href="{% url 'Take:task_take_division_hot' %}" class="info-title"><p><b>热&nbsp;门</b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/dm23.png' %}) no-repeat scroll left; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division_all' %}" class="info-title"><p><b><u>所&nbsp;有</u></b></p></a>
                          </div>
                      </li>
                  </ul>
              </div>
              <div class="main-cont main-user">
                  <ul class="main-cont__list clearfix" style="width: 85%;margin: 0px auto;">
                      <li class="item" style=" background: url({% static 'images/cate01.png' %}) no-repeat; background-size: cover; text-align: center;">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'delivery' %}" class="info-title"><p><b><u>快&nbsp;&nbsp;递</u></b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/cate02.png' %}) no-repeat; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'buy' %}" class="info-title"><p><b><u>代&nbsp;&nbsp;购</u></b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/cate03.png' %}) no-repeat; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'print' %}" class="info-title"><p><b><u>打&nbsp;&nbsp;印</u></b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/cate04.png' %}) no-repeat; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'umbrella' %}" class="info-title"><p><b><u>共&nbsp;&nbsp;享&nbsp;&nbsp;伞</u></b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/cate05.png' %}) no-repeat; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'others' %}" class="info-title"><p><b><u>其&nbsp;&nbsp;它</u></b></p></a>
                          </div>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
          <div class="main-cont main-recommend"  style="width: 89%;margin: 0px auto;">
              <div class="main-cont__title" style="margin: 0px auto;text-align: center;width: 100%;" >
                  <h3 style="font-size: 30px;font-weight: 700;">
                      {% if taskone %}
                          {% if taskone.task_category == 'delivery' %}快&nbsp;递&nbsp;任&nbsp;务
                          {% elif taskone.task_category == 'buy' %}代&nbsp;购&nbsp;任&nbsp;务
                          {% elif taskone.task_category == 'print' %}打&nbsp;印&nbsp;任&nbsp;务
                          {% elif taskone.task_category == 'umbrella'%}共&nbsp;享&nbsp;伞&nbsp;任&nbsp;务
                          {% elif taskone.task_category == 'others'%}其&nbsp;他&nbsp;任&nbsp;务
                          {% endif %}
                      {% else %}
                          <h6>还没有这一类别的任务！</h6>
                      {% endif %}
                  </h3>
                  <p class="list">
              </div>
              <ul class="main-cont__list clearfix">
                  {% if tasks %}
                      {% for task in tasks %}
                          <li class="item">
                              <img src="/media/{{ task.task_img }}" alt="#" class="img">
                              <div class="info">
                                  <a href="{% url 'Take:task_take_division_details' task.task_id %}" class="title">
                                     {% if task.task_category == 'delivery' %}取快递
                                     {% elif task.task_category == 'buy' %}代购
                                     {% elif task.task_category == 'print'%}打印
                                     {% elif task.task_category == 'umbrella'%}共享伞
                                     {% else %}其他
                                     {% endif %}
                                  </a>
                                  <span><span class="pp">❤</span> {{ task.send_collection_times}}&nbsp;&nbsp;&nbsp;</span>
                                  <span><span class="bb" >¥</span>&nbsp;{{ task.task_reward }}</span>
                                  <a href="{% url 'Take:task_take_division_details' task.task_id %}" class="icon-text__pink purchase">详情</a>
                              </div>
                          </li>
                      {% endfor %}
                  {% endif %}
              </ul>
              <div class="page"  style="width: 20%; margin: 0px auto;">
                  {% if data %}
                      <ul id="pages" class="pagination pagination-sm pagination-xs">
                          {% if data.first %}
                              <li><a href="?page=1">1</a></li>
                          {% endif %}
                          {% if data.left %}
                              {% if data.left_has_more %}
                                  <li><span>...</span></li>
                              {% endif %}
                              {% for i in data.left %}
                                  <li><a href="?page={{i}}">{{i}}</a></li>
                              {% endfor %}
                          {% endif %}
                          <li class="active"><a href="?page={{data.page}}">{{data.page}}</a></li>
                                {% if data.right %}
                                    {% for i in data.right %}
                                        <li><a href="?page={{i}}">{{i}}</a></li>
                                    {% endfor %}
                                    {% if data.right_has_more %}
                                        <li><span>...</span></li>
                                    {% endif %}
                                {% endif %}
                          {% if data.last %}
                              <li><a href="?page={{data.total_pages}}">{{data.total_pages}}</a></li>
                          {% endif %}
                    </ul>
                  {% endif %}
              </div>
          </div>
      </div>
  </div>
{% endblock %}

Take/templates/task_take_division_all.html
{% extends 'home.html' %}
{% load static %}
{% block title %}所有任务 {% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/reset.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/rec_gd.css' %}" type = "text/css"/>
    <link rel="stylesheet" href="{% static 'css/index02.css' %}" type = "text/css"/>
{% endblock %}

{% block content %}

  <div class="main">
      <div class="main-inner body-width">
      <span class="aa"><a href="{% url 'Take:task_take' %}" class="cate"><<返回接单首页</a></span>
          <div class="banner clearfix">
              <div class="main-cont main-cate" style="width: 89%;margin: 0px auto" >
                  <ul class="main-cont__list clearfix">
                      <li class="item" style=" background: url({% static 'images/dm22.png' %}) no-repeat right; background-size: cover;margin-right: 110px;margin-left: 100px">
                          <div class="info" >
                              <a href="{% url 'Take:task_take_division_hot' %}" class="info-title"><p><b>热&nbsp;门</b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/dm23.png' %}) no-repeat scroll left; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division_all' %}" class="info-title"><p><b><u>所&nbsp;有</u></b></p></a>
                          </div>
                      </li>
                  </ul>
              </div>

              <div class="main-cont main-user">
                  <ul class="main-cont__list clearfix" style="width: 85%;margin: 0px auto;">
                      <li class="item" style=" background: url({% static 'images/cate01.png' %}) no-repeat; background-size: cover; text-align: center;">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'delivery' %}" class="info-title"><p><b><u>快&nbsp;&nbsp;递</u></b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/cate02.png' %}) no-repeat; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'buy' %}" class="info-title"><p><b><u>代&nbsp;&nbsp;购</u></b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/cate03.png' %}) no-repeat; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'print' %}" class="info-title"><p><b><u>打&nbsp;&nbsp;印</u></b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/cate04.png' %}) no-repeat; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'umbrella' %}" class="info-title"><p><b><u>共&nbsp;&nbsp;享&nbsp;&nbsp;伞</u></b></p></a>
                          </div>
                      </li>
                      <li class="item" style=" background: url({% static 'images/cate05.png' %}) no-repeat; background-size: cover; ">
                          <div class="info">
                              <a href="{% url 'Take:task_take_division' 'others' %}" class="info-title"><p><b><u>其&nbsp;&nbsp;它</u></b></p></a>
                          </div>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
          <div class="main-cont main-recommend" style="width: 89%;margin: 0px auto;">
              <div style="margin: 0px auto;text-align: center;width: 100%;" class= "main-cont__title" >
                  <h3 style="font-size: 30px;font-weight: 700;">所&nbsp;有&nbsp;任&nbsp;务</h3>
                  <p class="list">
              </div>
              <ul class="main-cont__list clearfix">
                  {% if tasks %}
                      {% for task in tasks %}
                          <li class="item">
                              <img src="/media/{{ task.task_img }}" alt="#" class="img">
                              <div class="info">
                                  <a href="{% url 'Take:task_take_division_details' task.task_id %}" class="title">
                                     {% if task.task_category == 'delivery' %}取快递
                                     {% elif task.task_category == 'buy' %}代购
                                     {% elif task.task_category == 'print'%}打印
                                     {% elif task.task_category == 'umbrella'%}共享伞
                                     {% else %}其他
                                     {% endif %}
                                  </a>
                                  <span><span class="pp">❤</span> {{ task.send_collection_times}}&nbsp;&nbsp;&nbsp;</span>
                                  <span><span class="bb" >¥</span>&nbsp;{{ task.task_reward }}</span>
                                  <a href="{% url 'Take:task_take_division_details' task.task_id %}" class="icon-text__pink purchase">详情</a>
                              </div>
                          </li>
                      {% endfor %}
                  {% else %}
                      <h6>当前还没有任务！</h6>
                  {% endif %}
              </ul>
              <div class="page"  style="width: 20%; margin: 0px auto;">
                  {% if data %}
                      <ul id="pages" class="pagination pagination-sm pagination-xs">
                          {% if data.first %}
                              <li><a href="?page=1">1</a></li>
                          {% endif %}
                          {% if data.left %}
                              {% if data.left_has_more %}
                                  <li><span>...</span></li>
                              {% endif %}
                              {% for i in data.left %}
                                  <li><a href="?page={{i}}">{{i}}</a></li>
                              {% endfor %}
                          {% endif %}
                          <li class="active"><a href="?page={{data.page}}">{{data.page}}</a></li>
                                {% if data.right %}
                                    {% for i in data.right %}
                                        <li><a href="?page={{i}}">{{i}}</a></li>
                                    {% endfor %}
                                    {% if data.right_has_more %}
                                        <li><span>...</span></li>
                                    {% endif %}
                                {% endif %}
                          {% if data.last %}
                              <li><a href="?page={{data.total_pages}}">{{data.total_pages}}</a></li>
                          {% endif %}
                    </ul>
                  {% endif %}
              </div>
          </div>
      </div>
  </div>
{% endblock %}